name: XGBoost PROD Pipeline

on:
  push:
    branches:
      - main

env:
  DATABRICKS_HOST: https://dbc-18e69d3a-43bf.cloud.databricks.com
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  MLFLOW_TRACKING_URI: databricks
  MLFLOW_REGISTRY_URI: databricks

jobs:
  train-register-promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Debug Databricks env
        run: |
          echo "HOST=$DATABRICKS_HOST"
          echo "TRACKING=$MLFLOW_TRACKING_URI"
          echo "REGISTRY=$MLFLOW_REGISTRY_URI"
          echo "TOKEN LENGTH=${#DATABRICKS_TOKEN}"
          echo "TOKEN LENGTH=${{ secrets.DATABRICKS_TOKEN }}"

      - name: Train XGBoost model
        run: |
          python train_xgb.py

      - name: Register & Promote model
        run: |
          python register_and_promote.py
